# -*- coding: utf-8 -*-
"""bayesian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-onnC2m7VchkSNRG_7zYPpQ8wNIcLCH
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# Load the dataset (replace 'iris.csv' with your actual file path)
df = pd.read_csv('Iris.csv')

# Display first few rows (optional)
print(df.head())

# Prepare features and labels
# Adjust column names if different in your dataset
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

# Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Gaussian Naive Bayes model
model = GaussianNB()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Detailed classification report
print(classification_report(y_test, y_pred))

# Save predictions with actual labels to a CSV
results = X_test.copy()
results['Actual'] = y_test.values
results['Predicted'] = y_pred
results.to_csv('iris_predictions.csv', index=False)
print("Predictions saved to 'iris_predictions.csv'")

