# -*- coding: utf-8 -*-
"""linear_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ja8dN_IohR6jHJns15e2wyOIsfXmpral
"""

# Import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Load dataset
data = pd.read_csv("Salary_dataset.csv")

# Prepare input (X) and output (y)
X = data[['YearsExperience']]
y = data['Salary']

# Train the model
model = LinearRegression()
model.fit(X, y)

# Display equation
print("Intercept (b0):", model.intercept_)
print("Slope (b1):", model.coef_[0])

# Take user input for prediction
exp = float(input("Enter years of experience: "))
predicted_salary = model.predict([[exp]])
print(f"Predicted Salary for {exp} years of experience: {predicted_salary[0]:.2f}")

# ---- Plot the data and regression line ----
plt.scatter(X, y, color='blue', label='Actual Data')   # Actual salary points
plt.plot(X, model.predict(X), color='red', label='Regression Line')  # Best-fit line

# Highlight the predicted point
plt.scatter(exp, predicted_salary, color='green', s=100, label='Predicted Salary')

# Add labels and title
plt.title("Salary vs Experience")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.legend()
plt.show()

